name: Automatic Updates

on:
  schedule:
    - cron: "0 */2 * * *"  # Trigger every 2 hours
  push:
    branches:
      - master  # Trigger on pushes to the 'master' branch
  workflow_dispatch:  # Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Check out the code

    # Add "hi" to file.txt
    - name: Add "hi" to file.txt
      run: |
        echo "hi" >> file.txt  # Append "hi" to file.txt
        cat file.txt  # Print the content of file.txt to confirm

    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Build with Gradle
      run: ./gradlew run -Dorg.gradle.daemon=false -Dgithubtoken="Bearer ${{ secrets.GITHUB_TOKEN }}"

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Actions"
        git add file.txt
        git commit --allow-empty -m "[auto-update] Added 'hi' to file.txt"
        git push https://Axolotian-dev:${{ secrets.API_TOKEN_GITHUB }}@github.com/Axolotian-dev/test
