name: Update JSON file

on: [push,workflow_dispatch]

jobs:
  update_file:
    runs-on: ubuntu-latest  # This will run on the latest Ubuntu runner
    steps:
#--------------------    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_THING }}
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
#--------------------
      - name: Modify JSON file
        run: |
            import json
            
            # Define the JSON file
            json_file = "test.json"
      
            # List of keys and values to update
            new_data = {
                "key1": "value1",
                "key2": "value2",
                "key3": "value3"
            }
      
            # Read the existing JSON file
            try:
                with open(json_file, "r") as f:
                    current_data = json.load(f)
            except (FileNotFoundError, json.JSONDecodeError):
                current_data = {}
      
            # Update the JSON file based on new_data
            updated_data = {k: new_data[k] for k in new_data}
      
            # Write back the modified JSON
            with open(json_file, "w") as f:
                json.dump(updated_data, f, indent=4)
      
            # Commit the changes
            import subprocess
            subprocess.run(["git", "config", "--global", "user.name", "github-actions"])
            subprocess.run(["git", "config", "--global", "user.email", "github-actions@github.com"])
            subprocess.run(["git", "add", json_file])
            subprocess.run(["git", "commit", "-m", "Update JSON file"])
            subprocess.run(["git", "push"])
        shell: python
#--------------------
      - name: Commit and push changes
        run: |
          git add test.json
          git commit -m "Updated JSON"
          git push https://Axolotian-dev:${{ secrets.TOKEN_THING }}@github.com/${{ github.repository }}.git
