#API_TOKEN_GITHUB
name: Modify Test JSON File

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually from the GitHub interface

jobs:
  modify_test_json_file:
    runs-on: ubuntu-latest  # This will run on the latest Ubuntu runner

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_THING }}
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Modify JSON file
        run: |
          jq '.newKey = "newValue"' test.json > temp.json && mv temp.json test.json

      - name: Commit and push changes
        run: |
          git add test.json
          git commit -m "Add 'aaa' to messages"
          git push https://Axolotian-dev:${{ secrets.TOKEN_THING }}@github.com/${{ github.repository }}.git HEAD:main
        
