name: Update JSON file

on: [push,workflow_dispatch]

jobs:
  update_file:
    runs-on: ubuntu-latest  # This will run on the latest Ubuntu runner
    steps:
#--------------------    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_THING }}
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
#--------------------
      - name: Modify JSON file
        run: |
          KEYS_VALUES= {"key1": "value1", "key2": {"subkey1": "subvalue1"}, "key3": "value3"}
          jq --argjson kv "$KEYS_VALUES" '
            def clean(obj; ref): 
              if (obj | type) == "object" then 
                with_entries(select(.key as $k | ref | has($k))) | 
                map_values(if (ref[.key] | type) == "object" then clean(.value; ref[.key]) else ref[.key] end)
              else obj end;
            clean(.; $kv)' test.json > temp.json && mv temp.json test.json

#--------------------
      - name: Commit and push changes
        run: |
          git add test.json
          git commit -m "Updated JSON"
          git push https://Axolotian-dev:${{ secrets.TOKEN_THING }}@github.com/${{ github.repository }}.git
        
