name: Modify Test JSON File

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually from the GitHub interface

jobs:
  modify_test_json_file:
    runs-on: ubuntu-latest  # This will run on the latest Ubuntu runner

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_THING }}
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
      - name: Modify JSON file
        run: |
          KEYS_VALUES='{"key1": "value1", "key2": ["list1","list2"], "key3": "value3"}'
          jq --argjson kv "$KEYS_VALUES" 'with_entries(select(.key as $k | $kv | has($k))) + $kv' test.json > temp.json && mv temp.json test.json
      - name: Commit and push changes
        run: |
          git add test.json
          git commit -m "Add 'aaa' to messages"
          git push https://Axolotian-dev:${{ secrets.TOKEN_THING }}@github.com/${{ github.repository }}.git HEAD:main
