name: Update JSON file

on: [push,workflow_dispatch]

jobs:
  update_file:
    runs-on: ubuntu-latest  # This will run on the latest Ubuntu runner
    steps:
#--------------------    
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN_THING }}
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
#--------------------
      - name: Modify JSON file
        run: |
          # Define test data (an array of key-value objects)
          KEYS_VALUES='[
            {"name": "key1", "value": "value1"},
            {"name": "key2", "value": "value2"},
            {"name": "key3", "value": "value3"}
          ]'
          # Process each key-value pair
          for kv in $(echo "$KEYS_VALUES" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${kv} | base64 --decode | jq -r ${1}
            }
            key=$(_jq '.name')
            value=$(_jq '.value')
            # Update or add the key-value pair
            jq --arg key "$key" --arg value "$value" \
              'if has($key) then .[$key] = $value else . + {($key): $value} end' \
              test.json > temp.json && mv temp.json test.json
          done
          # Check the contents of the modified JSON
          cat test.json
          # Remove any keys in test.json not in the list
          jq --argjson kv "$KEYS_VALUES" '
            . |= with_entries(select(.key as $k | $kv | map(.name) | index($k)))' test.json > temp.json && mv temp.json test.json

#--------------------
      - name: Commit and push changes
        run: |
          git add test.json
          git commit -m "Updated JSON"
          git push https://Axolotian-dev:${{ secrets.TOKEN_THING }}@github.com/${{ github.repository }}.git
